### ISSUE TITLE
Incorrect behaviour when validating request body

### ISSUE THREAD

**Issue by pratik-sharma-1** [pb33f/libopenapi-validator#35]
Observed below two behaviours while testing the library:

### 1. Panics when a request for which the body has to be validated is called with a nil body

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1096e15]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
        /usr/local/opt/go/libexec/src/io/io.go:704 +0x55
github.com/pb33f/libopenapi-validator/requests.ValidateRequestSchema(0xc000256400, 0xc000166a00, {0xc000174000, 0x48f, 0x580}, {0xc00018a000, 0x2dc, 0x0?})
        /home/pratik/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.30/requests/validate_request.go:36 +0x85
github.com/pb33f/libopenapi-validator/requests.(*requestBodyValidator).ValidateRequestBody(0xc0004f3da0, 0xc000256400)
        /home/pratik/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.30/requests/validate_body.go:89 +0x485
main.main()
        /home/pratik/libopenapi-eval/main.go:38 +0x2e5

Process finished with the exit code 2

```

Code to reproduce:
```
package main

import (
	"fmt"
	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi-validator/requests"
	"io"
	"net/http"
)

func main() {
	//petstore spec
	petStoreSpecSource := "https://petstore3.swagger.io/api/v3/openapi.json"
	specBytes := readSpecFromURL(petStoreSpecSource)

	doc, err := libopenapi.NewDocument(specBytes)
	if err != nil {
		fmt.Println("error while creating open api spec document", err)
		return
	}

	// new PUT request with nil Body
	// body is mandatory as per the spec
	req, err := http.NewRequest("PUT", "https://somehost.com/api/v3/pet", nil)
	if err != nil {
		fmt.Println("error while creating new HTTP request", err)
		return
	}

	req.Header.Set("Content-Type", "application/json")

	v3Model, errs := doc.BuildV3Model()
	if len(errs) > 0 {
		fmt.Println("error while building a Open API spec V3 model", errs)
		return
	}

	reqBodyValidator := requests.NewRequestBodyValidator(&v3Model.Model)
	isSuccess, valErrs := reqBodyValidator.ValidateRequestBody(req)

	fmt.Println("is validation successful-", isSuccess)

	if len(valErrs) > 0 {
		fmt.Println("error while validating request body", valErrs)
		return
	}

}
func readSpecFromURL(url string) []byte {
	res, err := http.Get(url)
	if err != nil {
		panic(err)
	}

	defer res.Body.Close()

	specBytes, err := io.ReadAll(res.Body)
	if err != nil {
		panic(err)
	}

	return specBytes
}


```

### 2.  Does not return any validation error when called with a http.NoBody

Expected result : return appropriate validation error
Actual result : no error
```
package main

import (
	"fmt"
	"io"
	"net/http"

	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi-validator/requests"
)

func main() {
	//petstore spec
	petStoreSpecSource := "https://petstore3.swagger.io/api/v3/openapi.json"
	specBytes := readSpecFromURL(petStoreSpecSource)

	doc, err := libopenapi.NewDocument(specBytes)
	if err != nil {
		fmt.Println("error while creating open api spec document", err)
		return
	}

	// new PUT request with http.NoBody
	// body is mandatory as per the spec
	req, err := http.NewRequest("PUT", "https://somehost.com/api/v3/pet", http.NoBody)
	if err != nil {
		fmt.Println("error while creating new HTTP request", err)
		return
	}

	req.Header.Set("Content-Type", "application/json")

	v3Model, errs := doc.BuildV3Model()
	if len(errs) > 0 {
		fmt.Println("error while building a Open API spec V3 model", errs)
		return
	}

	reqBodyValidator := requests.NewRequestBodyValidator(&v3Model.Model)
	isSuccess, valErrs := reqBodyValidator.ValidateRequestBody(req)

	fmt.Println("is validation successful-", isSuccess)

	if len(valErrs) > 0 {
		fmt.Println("error while validating request body", valErrs)
		return
	}

}
func readSpecFromURL(url string) []byte {
	res, err := http.Get(url)
	if err != nil {
		panic(err)
	}

	defer res.Body.Close()

	specBytes, err := io.ReadAll(res.Body)
	if err != nil {
		panic(err)
	}

	return specBytes
}
```

**Comment by daveshanley** [comment]
Can you try again with v0.0.34?

**Comment by pratik-sharma-1** [comment]
I could not find the release v0.0.34. However, I tried by importing the main branch. It is working fine. Thanks a lot for a quick turn around!

**Comment by daveshanley** [comment]
I forgot to tag the release, it's been done now and `v0.0.34` is available
