### ISSUE TITLE
Incorrect Behavior While Validating Request Body 

### ISSUE THREAD

**Issue by triptesh1212** [pb33f/libopenapi-validator#75]
Observed below behavior while testing the library:

**Panics when a request for which the body has to be validated is called with a nil body**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x88 pc=0x104ffe140]

goroutine 1 [running]:
github.com/pb33f/libopenapi-validator/requests.ValidateRequestSchema(0x140001d8300, 0x14000334000, {0x14000020600, 0x161, 0x200}, {0x14000370000, 0xec, 0x104c707a4?})
	/Users/Triptesh/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.52/requests/validate_request.go:89 +0x390
github.com/pb33f/libopenapi-validator/requests.(*requestBodyValidator).ValidateRequestBody(0x14000249ee8, 0x140001d8300)
	/Users/Triptesh/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.52/requests/validate_body.go:101 +0x464
main.main()
	/Users/Triptesh/Downloads/go-test/main.go:40 +0x21c
exit status 2
```

Code to reproduce:
```
package main

import (
	"fmt"
	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi-validator/requests"
	"net/http"
	"os"
)

func main() {

	specBytes, _ := os.ReadFile("temp.json")

	doc, err := libopenapi.NewDocument(specBytes)
	if err != nil {
		fmt.Println("error while creating open api spec document", err)
		return
	}

	req, err := http.NewRequest("PUT", "/path1", nil)
	if err != nil {
		fmt.Println("error while creating new HTTP request", err)
		return
	}

	req.Header.Set("Content-Type", "application/json")

	v3Model, errs := doc.BuildV3Model()
	if len(errs) > 0 {
		fmt.Println("error while building a Open API spec V3 model", errs)
		return
	}

	reqBodyValidator := requests.NewRequestBodyValidator(&v3Model.Model)
	isSuccess, valErrs := reqBodyValidator.ValidateRequestBody(req)

	fmt.Println("is validation successful-", isSuccess)

	if len(valErrs) > 0 {
		fmt.Println("error while validating request body", valErrs)
		return
	}

}

```

temp.json ->

``` json
{
  "openapi": "3.0.1",
  "info": {
    "title": "testing",
    "description": "<p>This is for testing purpose</p>",
    "version": "1.0",
    "x-targetEndpoint": "https://mocktarget.apigee.net/json"
  },
  "servers": [
    {
      "url": "https://some-url.com"
    }
  ],
  "paths": {
    "/path1": {
      "put": {
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "age": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "name"
                    ]
                  },
                  {
                    "type": "object",
                    "properties": {
                      "email": {
                        "type": "string"
                      },
                      "address": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "email"
                    ]
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/path2": {
      "get": {
        "parameters": [
          {
            "name": "X-My-Header",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/path3": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}

```

**Comment by daveshanley** [comment]
Fixed in `v0.0.53`
